language: php

php:
  - 5.3
  - 5.4
  - 5.5

env:
  - SYMFONY_VERSION=origin/master

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install

script: phpunit --configuration Tests/phpunit.xml

notifications:
    email:
        - pawel.len@gmail.com
